# Generated by Django 2.1.7 on 2021-12-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pchead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_head_last_name', models.CharField(max_length=100)),
                ('pc_head_first_name', models.CharField(blank=True, max_length=100)),
                ('pc_head_phone', models.CharField(max_length=15)),
                ('pc_head_email', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcs_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Attendance.PCS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
