# Generated by Django 4.0 on 2021-12-24 13:16

import PC_attend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PCMember', '0001_initial'),
        ('Attendance', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(help_text='Enter the date of purchase', validators=[PC_attend.models.no_future])),
                ('present', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('Out of Town', 'Out of Town'), ('Sick', 'Sick'), ('Not_available', 'Not available')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PCMember.pcmember')),
                ('pcs_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Attendance.pcs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
