# Generated by Django 2.1.7 on 2021-12-21 19:18

import PC_attend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PCMember', '0002_auto_20211221_1918'),
        ('Attendance', '0003_auto_20211221_1918'),
        ('PCShead', '0003_auto_20211221_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PcAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(help_text='Enter the date of purchase', validators=[PC_attend.models.no_future])),
                ('present', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('Out of Town', 'Out of Town'), ('Sick', 'Sick'), ('Not_available', 'Not available')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PCMember.PcMember')),
                ('pcs_head', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PCShead.Pchead')),
                ('pcs_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Attendance.PCS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
