# Generated by Django 4.0 on 2021-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Out of Town', 'Out of Town'), ('Not_available', 'Not available')], max_length=100),
        ),
    ]
