# Generated by Django 4.0 on 2021-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0002_alter_pcattendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Not_available', 'Not available'), ('Out of Town', 'Out of Town'), ('Sick', 'Sick')], max_length=100),
        ),
    ]
