# Generated by Django 4.0 on 2021-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0004_alter_pcattendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Out of Town', 'Out of Town'), ('Not_available', 'Not available'), ('Sick', 'Sick')], max_length=100),
        ),
    ]
