# Generated by Django 2.1.7 on 2022-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0006_alter_pcattendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Not_available', 'Not available'), ('Out of Town', 'Out of Town')], max_length=100),
        ),
    ]
