# Generated by Django 2.1.7 on 2022-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0007_auto_20220105_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Out of Town', 'Out of Town'), ('Not_available', 'Not available'), ('Sick', 'Sick')], max_length=100),
        ),
    ]
