# Generated by Django 2.1.7 on 2022-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0008_auto_20220105_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Not_available', 'Not available'), ('Out of Town', 'Out of Town'), ('Sick', 'Sick')], max_length=100),
        ),
    ]
