# Generated by Django 2.1.7 on 2022-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0009_auto_20220114_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Out of Town', 'Out of Town'), ('Not_available', 'Not available')], max_length=100),
        ),
    ]
