# Generated by Django 4.0 on 2022-01-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0004_alter_pcmember_id'),
        ('PC_attend', '0013_alter_pcattendance_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcattendance',
            name='pc_member',
        ),
        migrations.AddField(
            model_name='pcattendance',
            name='pc_member',
            field=models.ManyToManyField(to='PCMember.PcMember'),
        ),
    ]
