# Generated by Django 3.2.11 on 2022-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0014_remove_pcattendance_pc_member_pcattendance_pc_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(blank=True, choices=[('Out of Town', 'Out of Town'), ('No_reason', 'No reason'), ('No_idea', 'No Idea'), ('Sick', 'Sick'), ('relocated', 'relocated')], max_length=100),
        ),
    ]
