# Generated by Django 3.2.11 on 2022-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0015_alter_pcattendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Out of Town', 'Out of Town'), ('No_idea', 'No Idea'), ('No_reason', 'No reason'), ('relocated', 'relocated')], max_length=100),
        ),
    ]
