# Generated by Django 3.2.11 on 2022-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_attend', '0017_alter_pcattendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcattendance',
            name='reason',
            field=models.CharField(blank=True, choices=[('relocated', 'relocated'), ('No_reason', 'No reason'), ('No_idea', 'No Idea'), ('Sick', 'Sick'), ('Out of Town', 'Out of Town')], max_length=100),
        ),
    ]
