# Generated by Django 4.0 on 2021-12-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PCShead', '0002_alter_pchead_id'),
        ('Attendance', '0002_alter_pcs_id'),
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_member_last_name', models.CharField(max_length=100)),
                ('pc_member_first_name', models.CharField(blank=True, max_length=100)),
                ('pc_member_phone', models.CharField(max_length=15, unique=True)),
                ('pc_member_house_address', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcs_head', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PCShead.pchead')),
                ('pcs_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Attendance.pcs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
