# Generated by Django 4.0 on 2021-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmember',
            name='pc_member_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
