# Generated by Django 2.1.7 on 2021-12-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmember',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Divorced', 'Divorced'), ('Married', 'Married'), ('Single', 'Single'), ('widow', 'widow')], max_length=50),
        ),
        migrations.AddField(
            model_name='pcmember',
            name='pc_member_othername',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pcmember',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pcmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
