# Generated by Django 2.1.7 on 2022-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0002_alter_pcmember_pc_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
