# Generated by Django 3.2.11 on 2022-01-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0004_alter_pcmember_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcmember',
            old_name='user',
            new_name='pcs_head',
        ),
    ]
