# Generated by Django 3.2.11 on 2022-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0005_rename_user_pcmember_pcs_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmember',
            name='chapel',
            field=models.CharField(blank=True, choices=[('Ezekial', 'Ezekial'), ('John', 'John'), ('Amos', 'Amos'), ('Revelation', 'Revelation'), ('Numbers', 'Numbers'), ('Acts/ Kings', 'Acts/Kings'), ('Ephessians', 'Ephessians'), ('Joel', 'Joel'), ('Proverbs', 'Proverbs'), ('Genesis', 'Genesis'), ('Samuel', 'Samuel'), ('Ruth', 'Ruth'), ('Luke', 'Luke'), ('Daniel', 'Daniel'), ('Psalms', 'Psalms'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Ezra', 'Ezra'), ('Esther', 'Esther'), ('Isaiah', 'Isaiah'), ('Joshua', 'Joshua'), ('Neremiah', 'Neremiah'), ('Jeremiah', 'Jeremiah')], max_length=100),
        ),
    ]
