# Generated by Django 3.2.11 on 2022-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCMember', '0007_alter_pcmember_chapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmember',
            name='chapel',
            field=models.CharField(blank=True, choices=[('Ruth', 'Ruth'), ('Psalms', 'Psalms'), ('Joshua', 'Joshua'), ('Matthew', 'Matthew'), ('Jeremiah', 'Jeremiah'), ('Mark', 'Mark'), ('Revelation', 'Revelation'), ('Ezra', 'Ezra'), ('Amos', 'Amos'), ('Esther', 'Esther'), ('Samuel', 'Samuel'), ('Neremiah', 'Neremiah'), ('Luke', 'Luke'), ('Genesis', 'Genesis'), ('Daniel', 'Daniel'), ('Numbers', 'Numbers'), ('Ezekial', 'Ezekial'), ('Isaiah', 'Isaiah'), ('Joel', 'Joel'), ('Proverbs', 'Proverbs'), ('Ephessians', 'Ephessians'), ('John', 'John'), ('Malachi', 'Malachi'), ('Acts/ Kings', 'Acts/Kings')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pcmember',
            name='pc_member_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
