# Generated by Django 3.2.11 on 2022-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_first_name_user_last_name_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chapel',
            field=models.CharField(blank=True, choices=[('Matthew', 'Matthew'), ('Joshua', 'Joshua'), ('John', 'John'), ('Jeremiah', 'Jeremiah'), ('Luke', 'Luke'), ('Ruth', 'Ruth'), ('Esther', 'Esther'), ('Psalms', 'Psalms'), ('Genesis', 'Genesis'), ('Ezra', 'Ezra'), ('Malachi', 'Malachi'), ('Revelation', 'Revelation'), ('Proverbs', 'Proverbs'), ('Ezekial', 'Ezekial'), ('Numbers', 'Numbers'), ('Neremiah', 'Neremiah'), ('Ephessians', 'Ephessians'), ('Daniel', 'Daniel'), ('Joel', 'Joel'), ('Isaiah', 'Isaiah'), ('Acts/ Kings', 'Acts/Kings'), ('Amos', 'Amos'), ('Samuel', 'Samuel'), ('Mark', 'Mark')], max_length=100),
        ),
    ]
