# Generated by Django 3.2.11 on 2022-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_chapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chapel',
            field=models.CharField(blank=True, choices=[('Joel', 'Joel'), ('Daniel', 'Daniel'), ('Joshua', 'Joshua'), ('Luke', 'Luke'), ('Jeremiah', 'Jeremiah'), ('Neremiah', 'Neremiah'), ('Amos', 'Amos'), ('Ezra', 'Ezra'), ('Genesis', 'Genesis'), ('Matthew', 'Matthew'), ('Esther', 'Esther'), ('Malachi', 'Malachi'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Numbers', 'Numbers'), ('Revelation', 'Revelation'), ('Acts/ Kings', 'Acts/Kings'), ('John', 'John'), ('Ephessians', 'Ephessians'), ('Ezekial', 'Ezekial'), ('Ruth', 'Ruth'), ('Samuel', 'Samuel'), ('Isaiah', 'Isaiah'), ('Mark', 'Mark')], max_length=100),
        ),
    ]
