# Generated by Django 3.2.11 on 2022-01-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_chapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chapel',
            field=models.CharField(blank=True, choices=[('Neremiah', 'Neremiah'), ('Jeremiah', 'Jeremiah'), ('Mark', 'Mark'), ('Samuel', 'Samuel'), ('Isaiah', 'Isaiah'), ('Luke', 'Luke'), ('Ruth', 'Ruth'), ('Proverbs', 'Proverbs'), ('Joel', 'Joel'), ('Numbers', 'Numbers'), ('Matthew', 'Matthew'), ('Daniel', 'Daniel'), ('Genesis', 'Genesis'), ('Ezekial', 'Ezekial'), ('Joshua', 'Joshua'), ('Revelation', 'Revelation'), ('Ezra', 'Ezra'), ('John', 'John'), ('Amos', 'Amos'), ('Malachi', 'Malachi'), ('Acts/ Kings', 'Acts/Kings'), ('Esther', 'Esther'), ('Ephessians', 'Ephessians'), ('Psalms', 'Psalms')], max_length=100),
        ),
    ]
