# Generated by Django 3.2.11 on 2022-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_chapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chapel',
            field=models.CharField(blank=True, choices=[('Psalms', 'Psalms'), ('Ruth', 'Ruth'), ('Joshua', 'Joshua'), ('Matthew', 'Matthew'), ('Jeremiah', 'Jeremiah'), ('Mark', 'Mark'), ('Revelation', 'Revelation'), ('Ezra', 'Ezra'), ('Esther', 'Esther'), ('Samuel', 'Samuel'), ('Neremiah', 'Neremiah'), ('Luke', 'Luke'), ('Acts/ Kings', 'Acts/Kings'), ('Genesis', 'Genesis'), ('Daniel', 'Daniel'), ('Numbers', 'Numbers'), ('Ezekial', 'Ezekial'), ('Isaiah', 'Isaiah'), ('Joel', 'Joel'), ('Proverbs', 'Proverbs'), ('Ephessians', 'Ephessians'), ('John', 'John'), ('Malachi', 'Malachi'), ('Amos', 'Amos')], max_length=100),
        ),
    ]
